---
title: "Lab 06 - Functions and iterations"
author: "Duncan Hoyland"
date: "`r Sys.Date()`"
output: html_document
---


### Packages and Data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(ggplot2)
```

```{r diamon_rename}
diamonds <- diamonds %>% rename(
    depth_pct = depth,
    length_mm = x,
    width_mm = y,
    depth_mm = z,
    table_pct = table
  )
```


## Exercise 1

```{r}
colSums(is.na(diamonds))
# No NAs present in the data set 

clean_diamonds <- diamonds %>% 
  filter(length_mm > 0 & width_mm > 0 & depth_mm > 0)

clean_diamonds %>% 
  group_by(cut) %>% 
  summarise(count = n(),
            mean_price = mean(price),
            min_price = min(price),
            max_price = max(price))
clean_diamonds %>% 
  group_by(color) %>% 
  summarise(count = n(),
            mean_price = mean(price),
            min_price = min(price),
            max_price = max(price))
clean_diamonds %>% 
  group_by(clarity) %>% 
  summarise(count = n(), 
            mean_price = mean(price), 
            min_price = min(price), 
            max_price = max(price))

ggplot(data = clean_diamonds,
       mapping = aes(x = carat,
                     y = price,
                     colour = cut,
                     alpha = 0.05)) +
  geom_point(size = 1) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Scatter Plot of Carat against Price",
       subtitle = "Colours represent Cut",
       x = "Carat (weight of diamond)",
       y = "Price (USD)",
       colour = "") +
  guides(alpha = "none") +
  theme(legend.position = "bottom")
```


## Exercise 2

```{r}
clean_diamonds <- clean_diamonds %>%
  mutate(table_mm = table_pct * width_mm / 100)

# Overall table_mm arithmetic mean?
clean_diamonds %>% 
  summarise(mean_table_mm = mean(table_mm))
# table_mm arithmetic mean within each clarity category
clean_diamonds %>% 
  group_by(clarity) %>%
  summarise(mean_table_mm = mean(table_mm))
```

As the clarity of the diamond increases the average table length decreases

```{r}
# calculate the arithmetic mean across all numeric variables
clean_diamonds %>% 
  summarise(across(where(is.numeric),
              \(x) mean(x, na.rm = TRUE),
              .names = "avg_{.col}"))




```

## Exercise 3

```{r}
gmean <- function(x){
  if(any(!is.numeric(x)) || any(x <= 0)) {
    warning("X inputs must be greater than zero and numerical for geometric mean calculations")
    return(NaN)
  }
  geometric_mean <- exp(mean(log(x)))
  
  return(geometric_mean)
}
```

## Exercise 4

```{r, error = TRUE}

test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
  test4 = c(0.38,  0.94, -1.56),
  test5 = c(TRUE, TRUE),
  test6 = c("6", "7", "8")
)


# Create for loop to test gmean() on the above examples
for (i in seq_along(test_data)) {
  gmean_output <- gmean(test_data[[i]])
}

```


## Exercise 6

```{r}
# replicate the for loop from Ex 4 using the map (or a similar) function

```


## Exercise 7

```{r}
# Overall table_mm arithmetic mean, median, and geometric mean?






# Arithmetic mean, median, and geometric mean of table_mm within each clarity category






```

_Add your comment here_
